from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture(scope="session")
def root() -> Path:
    return ROOT


@pytest.fixture(scope="session")
def template(root: Path) -> dict:
    return json.loads((root / "coworld_manifest_template.json").read_text(encoding="utf-8"))


@pytest.fixture(scope="session")
def tiny_video(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A 3 s synthetic clip with audio, generated by ffmpeg; fast and deterministic."""
    out = tmp_path_factory.mktemp("media") / "tiny.mp4"
    subprocess.run(
        [
            "ffmpeg",
            "-v",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            "testsrc2=size=1280x720:rate=24:duration=3",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=3",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-shortest",
            str(out),
        ],
        check=True,
    )
    return out


@pytest.fixture(scope="session")
def tiny_image(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A 640x360 PNG generated by ffmpeg."""
    out = tmp_path_factory.mktemp("media") / "tiny.png"
    subprocess.run(
        [
            "ffmpeg",
            "-v",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            "testsrc2=size=640x360:rate=1:duration=1",
            "-frames:v",
            "1",
            str(out),
        ],
        check=True,
    )
    return out
